title: Address Book
description: A program that maintains contact information and dated notes for each individual.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
